### ISSUE TITLE
downloading contracts without exhausting site limits

### ISSUE THREAD

**Issue by shashank-srikant** [tintinweb/pyetherchain#1]
@tintinweb 
i was wondering if you've figured out how to throttle requesting etherchain.

on running your script, it quickly starts producing a 402 error.
https://github.com/tintinweb/pyetherchain/blob/master/examples/download_contracts.py

are there optimal batch, amount sizes you've figured out to ensure this doesn't happen?
i'm trying to pull out at least 10^6 codes from there.

thanks!

**Comment by tintinweb** [comment]
Hi @shashank-srikant,

The script currently performs more requests than needed to get contract objects and transactions. I am planning to change the design to lazy loading information from etherchain in the future. If that would be of help I can provide you with a minimal download script before tackling the lazy loading (currently for etherscan.io with throtteling, should be easily adaptable by using the EtherchainApi class).

cheers

**Comment by shashank-srikant** [comment]
sure, that would be very helpful! would you be uploading it to the examples folder?
and thank you for putting up this library. very useful!

PS -
to clarify, i do have a list of addresses that i want to access. but looping through and calling get-source in a naive way is an issue. i'm trying out changing IP addresses dynamically. will post a pull request to the example if it works out. that'll be a handy trick for others to use as well, i'm guessing.

**Comment by tintinweb** [comment]
Here's an untested quick shot on directly using the etherchain api object massively reducing the request overhead needed to download the source.

```python
from pyetherchain.pyetherchain import EtherChainApi

api = EtherChainApi()
for address in ('0x....', '0x...', ... ):
    src = api.get_account_source(address)

```

**Comment by shashank-srikant** [comment]
thanks; i too had added a proxy cycling feature and used the `get_account_source` method to fetch codes. i even modified your script to cycle through random user-agent strings.
in spite of these measures, it gets blocked after ~100 pulls.

**Comment by tintinweb** [comment]
The lazy loading functionality will be added with a future releases. this way we also avoid putting too much load on etherchains infrastruct. They're providing a nice service therefore we should also play nice with what we build here. As a proxy cycling feature is circumventing their measures I feel like this is not something that should be part of this tool.

**Comment by tintinweb** [comment]
* added examples/[download_contracts_etherscan_io.py](https://github.com/tintinweb/pyetherchain/blob/master/examples/download_contracts_etherscan_io.py)
* added proxy to UA and refactored some code 4d29bf93913135314eabc055768bbcaac5398b6f fixing #2

**Comment by tintinweb** [comment]
tracking the lazy loading as #3 and closing this issue. feel free to open it in case you have more questions.
