### ISSUE TITLE
Cannot compile examples from source

### ISSUE THREAD

**Issue by dmtx97** [tintinweb/pyetherchain#7]
I know this is not a maintained project of yours, but I am in need of a way to download the contract code directly from etherscan for research analysis and your project seems to be the only one I've seen to do this. I get random compiler errors when I run the code. I've tried modifying it with no avail. Can you look into this please?  Thanks!

**Comment by tintinweb** [comment]
Hi @dmtx97,

I've published a script to download from etherscan.io here --> https://github.com/tintinweb/smart-contract-sanctuary
This repo is all about etherchain.org

regarding the compiler errors. I suggest to post one of the traces here as that might suggest why it does not compile.

cheers,
tin

**Comment by dmtx97** [comment]
> Hi @dmtx97,
> 
> I've published a script to download from etherscan.io here --> https://github.com/tintinweb/smart-contract-sanctuary
> This repo is all about etherchain.org
> 
> regarding the compiler errors. I suggest to post one of the traces here as that might suggest why it does not compile.
> 
> cheers,
> tin

Thanks for reaching out! I decided to implement my own using the API which works similarly to how yours does! Thanks again and sorry for the inconvenience!

**Comment by tintinweb** [comment]
always happy to help.

cheers,
tin
